#!/bin/bash

SERVER_URL=127.0.0.1:8000
USER_EMAIL=crosquillas@gmail.com
USER_PASS=tijuas

# Auth
http POST $SERVER_URL/rest-auth/login/ "email=$USER_EMAIL" "password=$USER_PASS"

# Dynamic auth header based on environment variables
AUTH_HEADER="Authorization: Token $(http POST $SERVER_URL/rest-auth/login/ "email=$USER_EMAIL" "password=$USER_PASS" | jq -r .key)"

# Locations
http GET $SERVER_URL/api/v2/locations/ $AUTH_HEADER
